language: ruby
rvm:
  - 2.3.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
